<?php

namespace Database\Seeders;

use App\Models\Scholarship;
use App\Models\ScholarshipProvider;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class IndonesianScholarshipSeeder extends Seeder
{
    /**
     * Seed data mock beasiswa Indonesia berbahasa Indonesia.
     */
    public function run(): void
    {
        $providers = [
            'Kemendikbud' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Kementerian Pendidikan dan Kebudayaan RI'],
                [
                    'website' => 'https://www.knb.kemdikbud.go.id',
                    'description' => 'Program beasiswa pemerintah Indonesia untuk mahasiswa internasional.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'UI' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Universitas Indonesia'],
                [
                    'website' => 'https://www.ui.ac.id',
                    'description' => 'Program beasiswa internasional Universitas Indonesia.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'UGM' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Universitas Gadjah Mada'],
                [
                    'website' => 'https://www.ugm.ac.id',
                    'description' => 'Program beasiswa UGM untuk mahasiswa berprestasi.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'ITB' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Institut Teknologi Bandung'],
                [
                    'website' => 'https://www.itb.ac.id',
                    'description' => 'Program beasiswa ITB untuk bidang teknik dan sains.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'LPDP' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'LPDP Kementerian Keuangan RI'],
                [
                    'website' => 'https://www.lpdp.kemenkeu.go.id',
                    'description' => 'Beasiswa dana abadi pendidikan untuk studi lanjut.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'BINUS' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'BINUS University'],
                [
                    'website' => 'https://www.binus.ac.id',
                    'description' => 'Beasiswa prestasi BINUS untuk program sarjana.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'UNAIR' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Universitas Airlangga'],
                [
                    'website' => 'https://www.unair.ac.id',
                    'description' => 'Beasiswa unggulan UNAIR untuk mahasiswa internasional.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'UNDIP' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Universitas Diponegoro'],
                [
                    'website' => 'https://www.undip.ac.id',
                    'description' => 'Program beasiswa internasional UNDIP.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'UNS' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Universitas Sebelas Maret'],
                [
                    'website' => 'https://www.uns.ac.id',
                    'description' => 'Beasiswa UNS untuk program pascasarjana.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'Telkom' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Telkom University'],
                [
                    'website' => 'https://www.telkomuniversity.ac.id',
                    'description' => 'Beasiswa inovasi untuk teknologi dan bisnis.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'UB' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Universitas Brawijaya'],
                [
                    'website' => 'https://www.ub.ac.id',
                    'description' => 'Dukungan finansial bagi mahasiswa internasional UB.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
            'UNPAD' => ScholarshipProvider::query()->updateOrCreate(
                ['name' => 'Universitas Padjadjaran'],
                [
                    'website' => 'https://www.unpad.ac.id',
                    'description' => 'Program beasiswa prestasi untuk mahasiswa pascasarjana.',
                    'country' => 'Indonesia',
                    'is_verified' => true,
                ]
            ),
        ];

        $scholarships = [
            [
                'provider' => 'Kemendikbud',
                'title' => 'Beasiswa Pemerintah Indonesia (KNB)',
                'description' => 'Program Kemitraan Negara Berkembang (KNB) untuk mahasiswa dari negara berkembang yang ingin menempuh studi S2 atau S3 di universitas unggulan Indonesia.',
                'amount' => 50000000,
                'currency' => 'IDR',
                'type' => 'full',
                'level' => 'master',
                'target_level' => 's1',
                'degree_level' => 's2',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['teknik', 'ilmu sosial', 'ilmu alam', 'ekonomi'],
                'minimum_gpa' => 2.75,
                'language_requirements' => ['toefl_ibt' => 61, 'ielts' => 6.0],
                'application_deadline' => Carbon::parse('2026-03-31')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 24,
                'application_url' => 'https://www.knb.kemdikbud.go.id',
                'requirements' => [
                    'Lulusan S1 dengan IPK minimal 2.75',
                    'Sertifikat TOEFL iBT 61 atau IELTS 6.0',
                    'Dua surat rekomendasi',
                    'Surat keterangan sehat',
                    'Pernyataan tujuan studi',
                ],
                'benefits' => [
                    'Biaya kuliah penuh',
                    'Tunjangan hidup bulanan',
                    'Dukungan akomodasi',
                    'Asuransi kesehatan',
                    'Tunjangan kedatangan awal',
                ],
                'selection_criteria' => ['Kelengkapan berkas', 'Kemampuan akademik', 'Motivasi studi'],
                'application_process' => ['Daftar online', 'Unggah dokumen', 'Seleksi administrasi', 'Pengumuman'],
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'provider' => 'UI',
                'title' => 'Beasiswa Internasional Universitas Indonesia',
                'description' => 'Beasiswa berbasis prestasi untuk mahasiswa internasional program sarjana di Universitas Indonesia.',
                'amount' => 230000000,
                'currency' => 'IDR',
                'type' => 'merit',
                'level' => 'bachelor',
                'target_level' => 'sma',
                'degree_level' => 's1',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['ilmu komputer', 'bisnis', 'kedokteran', 'teknik', 'ilmu sosial'],
                'minimum_gpa' => 3.20,
                'language_requirements' => ['toefl_ibt' => 80, 'ielts' => 6.5],
                'application_deadline' => Carbon::parse('2026-04-15')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 48,
                'application_url' => 'https://www.ui.ac.id',
                'requirements' => [
                    'Lulusan SMA/sederajat dengan nilai unggul',
                    'TOEFL iBT 80 atau IELTS 6.5',
                    'Esai personal',
                    'Transkrip akademik',
                    'Dua surat referensi',
                ],
                'benefits' => [
                    'Pembebasan biaya kuliah sebagian atau penuh',
                    'Tunjangan bulanan',
                    'Bantuan akomodasi',
                    'Kursus Bahasa Indonesia',
                ],
                'selection_criteria' => ['Prestasi akademik', 'Esai', 'Rekomendasi'],
                'application_process' => ['Pendaftaran online', 'Seleksi dokumen', 'Pengumuman hasil'],
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'provider' => 'UGM',
                'title' => 'Beasiswa Universitas Gadjah Mada untuk Mahasiswa Internasional',
                'description' => 'Program beasiswa UGM bagi mahasiswa internasional berprestasi untuk studi pascasarjana.',
                'amount' => 24000000,
                'currency' => 'IDR',
                'type' => 'full',
                'level' => 'master',
                'target_level' => 's1',
                'degree_level' => 's2',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['teknik', 'pertanian', 'kedokteran', 'ekonomi', 'hukum'],
                'minimum_gpa' => 3.00,
                'language_requirements' => ['toefl_ibt' => 70, 'ielts' => 6.0],
                'application_deadline' => Carbon::parse('2026-03-20')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 24,
                'application_url' => 'https://www.ugm.ac.id',
                'requirements' => [
                    'Lulusan S1 dengan IPK minimal 3.0',
                    'TOEFL iBT 70 atau IELTS 6.0',
                    'Proposal riset',
                    'CV akademik',
                    'Dua surat rekomendasi',
                ],
                'benefits' => [
                    'Biaya kuliah penuh',
                    'Tunjangan hidup bulanan',
                    'Dana riset',
                    'Dukungan konferensi',
                ],
                'selection_criteria' => ['IPK', 'Proposal riset', 'Rekomendasi'],
                'application_process' => ['Daftar online', 'Seleksi administrasi', 'Wawancara'],
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'provider' => 'ITB',
                'title' => 'Beasiswa Internasional ITB',
                'description' => 'Beasiswa bagi calon mahasiswa internasional berbakat di bidang teknik dan teknologi di ITB.',
                'amount' => 70000000,
                'currency' => 'IDR',
                'type' => 'full',
                'level' => 'bachelor',
                'target_level' => 'sma',
                'degree_level' => 's1',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['teknik', 'ilmu komputer', 'arsitektur', 'desain', 'sains'],
                'minimum_gpa' => 3.20,
                'language_requirements' => ['toefl_ibt' => 75, 'ielts' => 6.0],
                'application_deadline' => Carbon::parse('2026-04-30')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 48,
                'application_url' => 'https://www.itb.ac.id',
                'requirements' => [
                    'Lulusan SMA dengan latar belakang STEM kuat',
                    'TOEFL iBT 75 atau IELTS 6.0',
                    'Skor ujian masuk atau SAT',
                    'Portofolio untuk desain/arsitektur',
                    'Esai motivasi',
                ],
                'benefits' => [
                    'Biaya kuliah penuh',
                    'Bantuan biaya hidup sebagian',
                    'Bantuan akomodasi',
                    'Pendampingan akademik',
                ],
                'selection_criteria' => ['Kinerja akademik', 'Portofolio', 'Potensi'],
                'application_process' => ['Registrasi', 'Unggah dokumen', 'Tes/seleksi', 'Pengumuman'],
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'provider' => 'LPDP',
                'title' => 'Beasiswa LPDP Dana Abadi Pendidikan',
                'description' => 'Beasiswa komprehensif LPDP untuk studi S2 dengan fokus pada prioritas pembangunan nasional.',
                'amount' => 160000000,
                'currency' => 'IDR',
                'type' => 'full',
                'level' => 'master',
                'target_level' => 's1',
                'degree_level' => 's2',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['Indonesia'],
                'fields_of_study' => ['semua bidang'],
                'minimum_gpa' => 3.00,
                'language_requirements' => ['toefl_ibt' => 80, 'ielts' => 6.5],
                'application_deadline' => Carbon::parse('2026-05-15')->toDateString(),
                'start_date' => Carbon::parse('2026-10-01')->toDateString(),
                'duration_months' => 24,
                'application_url' => 'https://www.lpdp.kemenkeu.go.id',
                'requirements' => [
                    'Lulusan S1 dengan IPK minimal 3.0',
                    'TOEFL iBT 80 atau IELTS 6.5',
                    'Surat komitmen kontribusi untuk Indonesia',
                    'Proposal studi',
                    'Pengalaman kepemimpinan',
                ],
                'benefits' => [
                    'Biaya kuliah penuh',
                    'Biaya hidup',
                    'Asuransi kesehatan',
                    'Tunjangan buku',
                    'Dana riset',
                    'Dukungan konferensi',
                ],
                'selection_criteria' => ['Administrasi', 'Tes bakat skolastik', 'Wawancara'],
                'application_process' => ['Pendaftaran online', 'Seleksi administrasi', 'Seleksi substansi'],
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'provider' => 'BINUS',
                'title' => 'Beasiswa Prestasi BINUS University',
                'description' => 'Beasiswa prestasi untuk calon mahasiswa sarjana di BINUS dengan rekam jejak akademik unggul.',
                'amount' => 35000000,
                'currency' => 'IDR',
                'type' => 'partial',
                'level' => 'bachelor',
                'target_level' => 'sma',
                'degree_level' => 's1',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['ilmu komputer', 'bisnis', 'desain', 'teknik', 'komunikasi'],
                'minimum_gpa' => 3.50,
                'language_requirements' => ['toefl_ibt' => 61, 'ielts' => 5.5],
                'application_deadline' => Carbon::parse('2026-06-01')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 48,
                'application_url' => 'https://www.binus.ac.id',
                'requirements' => [
                    'Lulusan SMA dengan nilai tinggi',
                    'TOEFL iBT 61 atau IELTS 5.5',
                    'Esai aplikasi',
                    'Dokumen prestasi akademik/non-akademik',
                    'Wawancara untuk kandidat terpilih',
                ],
                'benefits' => [
                    'Potongan biaya kuliah 25% sampai 75%',
                    'Pengakuan prestasi akademik',
                    'Akses program internasional',
                    'Dukungan pengembangan karier',
                ],
                'selection_criteria' => ['Nilai akademik', 'Prestasi', 'Wawancara'],
                'application_process' => ['Pendaftaran', 'Verifikasi berkas', 'Wawancara'],
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'provider' => 'UNAIR',
                'title' => 'Beasiswa Unggulan Universitas Airlangga',
                'description' => 'Program beasiswa kompetitif untuk mahasiswa internasional jenjang S2 di UNAIR.',
                'amount' => 18000000,
                'currency' => 'IDR',
                'type' => 'merit',
                'level' => 'master',
                'target_level' => 's1',
                'degree_level' => 's2',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['kedokteran', 'kesehatan masyarakat', 'hukum', 'ekonomi', 'ilmu sosial'],
                'minimum_gpa' => 3.25,
                'language_requirements' => ['toefl_ibt' => 70, 'ielts' => 6.0],
                'application_deadline' => Carbon::parse('2026-03-10')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 24,
                'application_url' => 'https://www.unair.ac.id',
                'requirements' => [
                    'Lulusan S1 dengan IPK minimal 3.25',
                    'TOEFL iBT 70 atau IELTS 6.0',
                    'Transkrip akademik',
                    'Proposal riset',
                    'Dua surat rekomendasi',
                ],
                'benefits' => [
                    'Biaya kuliah penuh',
                    'Tunjangan bulanan',
                    'Pendanaan riset',
                    'Pelatihan Bahasa Indonesia',
                ],
                'selection_criteria' => ['IPK', 'Kualitas proposal', 'Rekomendasi'],
                'application_process' => ['Daftar online', 'Seleksi dokumen', 'Wawancara'],
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'provider' => 'UNDIP',
                'title' => 'Beasiswa Program Internasional Universitas Diponegoro',
                'description' => 'Bantuan finansial bagi mahasiswa internasional yang mengikuti program internasional di UNDIP.',
                'amount' => 25000000,
                'currency' => 'IDR',
                'type' => 'partial',
                'level' => 'bachelor',
                'target_level' => 'sma',
                'degree_level' => 's1',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['teknik', 'kedokteran', 'ekonomi', 'sains', 'perikanan'],
                'minimum_gpa' => 3.00,
                'language_requirements' => ['toefl_ibt' => 60, 'ielts' => 5.5],
                'application_deadline' => Carbon::parse('2026-04-20')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 48,
                'application_url' => 'https://www.undip.ac.id',
                'requirements' => [
                    'Ijazah SMA/sederajat dengan nilai baik',
                    'TOEFL iBT 60 atau IELTS 5.5',
                    'Esai personal',
                    'Dokumen akademik',
                    'Salinan paspor',
                ],
                'benefits' => [
                    'Potongan biaya kuliah 50%',
                    'Pendampingan akademik',
                    'Program integrasi budaya',
                    'Pilihan akomodasi kampus',
                ],
                'selection_criteria' => ['Administrasi', 'Kelayakan akademik'],
                'application_process' => ['Pendaftaran', 'Verifikasi dokumen', 'Pengumuman'],
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'provider' => 'UNS',
                'title' => 'Beasiswa Pascasarjana Universitas Sebelas Maret',
                'description' => 'Kesempatan beasiswa bagi mahasiswa pascasarjana di UNS dengan fokus pada bidang unggulan kampus.',
                'amount' => 60000000,
                'currency' => 'IDR',
                'type' => 'full',
                'level' => 'master',
                'target_level' => 's1',
                'degree_level' => 's2',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['pertanian', 'pendidikan', 'teknik', 'ilmu sosial'],
                'minimum_gpa' => 3.00,
                'language_requirements' => ['toefl_ibt' => 65, 'ielts' => 5.5],
                'application_deadline' => Carbon::parse('2026-05-01')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 24,
                'application_url' => 'https://www.uns.ac.id',
                'requirements' => [
                    'Lulusan S1 dengan IPK minimal 3.0',
                    'TOEFL iBT 65 atau IELTS 5.5',
                    'Proposal riset',
                    'CV akademik',
                    'Dua surat referensi',
                ],
                'benefits' => [
                    'Biaya kuliah penuh',
                    'Akses perpustakaan dan laboratorium',
                    'Pendampingan akademik',
                    'Fasilitas riset',
                ],
                'selection_criteria' => ['IPK', 'Proposal', 'Kelengkapan dokumen'],
                'application_process' => ['Registrasi', 'Seleksi berkas', 'Pengumuman'],
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'provider' => 'Telkom',
                'title' => 'Beasiswa Inovasi Telkom University',
                'description' => 'Beasiswa untuk calon mahasiswa yang memiliki potensi inovasi di bidang teknologi dan bisnis.',
                'amount' => 150000000,
                'currency' => 'IDR',
                'type' => 'merit',
                'level' => 'bachelor',
                'target_level' => 'sma',
                'degree_level' => 's1',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['ilmu komputer', 'teknologi informasi', 'telekomunikasi', 'bisnis'],
                'minimum_gpa' => 3.20,
                'language_requirements' => ['toefl_ibt' => 60, 'ielts' => 5.5],
                'application_deadline' => Carbon::parse('2026-06-15')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 48,
                'application_url' => 'https://www.telkomuniversity.ac.id',
                'requirements' => [
                    'Lulusan SMA dengan nilai baik',
                    'TOEFL iBT 60 atau IELTS 5.5',
                    'Portofolio proyek inovasi',
                    'Esai personal',
                    'Satu surat rekomendasi',
                ],
                'benefits' => [
                    'Pembebasan biaya kuliah sebagian atau penuh',
                    'Akses laboratorium inovasi',
                    'Mentoring industri',
                    'Dukungan inkubasi startup',
                ],
                'selection_criteria' => ['Inovasi', 'Akademik', 'Wawancara'],
                'application_process' => ['Pendaftaran', 'Review portofolio', 'Wawancara'],
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'provider' => 'UB',
                'title' => 'Beasiswa Mahasiswa Internasional Universitas Brawijaya',
                'description' => 'Dukungan pembiayaan bagi mahasiswa internasional di UB untuk program sarjana dan pascasarjana.',
                'amount' => 30000000,
                'currency' => 'IDR',
                'type' => 'partial',
                'level' => 'bachelor',
                'target_level' => 'sma',
                'degree_level' => 's1',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['pertanian', 'teknik', 'kedokteran', 'ekonomi', 'hukum'],
                'minimum_gpa' => 3.00,
                'language_requirements' => ['toefl_ibt' => 60, 'ielts' => 5.5],
                'application_deadline' => Carbon::parse('2026-03-25')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 48,
                'application_url' => 'https://www.ub.ac.id',
                'requirements' => [
                    'Sertifikat akademik dengan nilai baik',
                    'TOEFL iBT 60 atau IELTS 5.5',
                    'Pernyataan tujuan studi',
                    'Surat keterangan sehat',
                    'Surat jaminan finansial',
                ],
                'benefits' => [
                    'Subsidi biaya kuliah',
                    'Bantuan biaya hidup sebagian',
                    'Bantuan proses visa pelajar',
                    'Program orientasi budaya',
                ],
                'selection_criteria' => ['Kelengkapan dokumen', 'Kelayakan akademik'],
                'application_process' => ['Daftar online', 'Verifikasi berkas', 'Pengumuman'],
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'provider' => 'UNPAD',
                'title' => 'Beasiswa Prestasi Universitas Padjadjaran',
                'description' => 'Beasiswa prestisius bagi mahasiswa pascasarjana di UNPAD, khususnya bidang kesehatan dan ilmu sosial.',
                'amount' => 90000000,
                'currency' => 'IDR',
                'type' => 'full',
                'level' => 'doctorate',
                'target_level' => 's2',
                'degree_level' => 's3',
                'target_countries' => ['Indonesia'],
                'eligible_nationalities' => ['*'],
                'fields_of_study' => ['kedokteran', 'kedokteran gigi', 'pertanian', 'komunikasi', 'psikologi'],
                'minimum_gpa' => 3.25,
                'language_requirements' => ['toefl_ibt' => 75, 'ielts' => 6.0],
                'application_deadline' => Carbon::parse('2026-04-10')->toDateString(),
                'start_date' => Carbon::parse('2026-09-01')->toDateString(),
                'duration_months' => 48,
                'application_url' => 'https://www.unpad.ac.id',
                'requirements' => [
                    'Lulusan S2 dengan IPK minimal 3.25',
                    'TOEFL iBT 75 atau IELTS 6.0',
                    'Proposal riset',
                    'Rekam publikasi ilmiah',
                    'Dua surat rekomendasi',
                ],
                'benefits' => [
                    'Biaya kuliah penuh',
                    'Tunjangan hidup bulanan',
                    'Dana riset',
                    'Pendanaan konferensi',
                    'Dukungan publikasi',
                ],
                'selection_criteria' => ['Akademik', 'Proposal', 'Publikasi', 'Wawancara'],
                'application_process' => ['Pendaftaran online', 'Seleksi dokumen', 'Wawancara akhir'],
                'status' => 'active',
                'is_featured' => true,
            ],
        ];

        foreach ($scholarships as $item) {
            $provider = $providers[$item['provider']];

            Scholarship::query()->updateOrCreate(
                [
                    'provider_id' => $provider->id,
                    'title' => $item['title'],
                ],
                [
                    'description' => $item['description'],
                    'amount' => $item['amount'],
                    'currency' => $item['currency'],
                    'type' => $item['type'],
                    'level' => $item['level'],
                    'target_level' => $item['target_level'],
                    'degree_level' => $item['degree_level'],
                    'target_countries' => json_encode($item['target_countries'], JSON_UNESCAPED_UNICODE),
                    'eligible_nationalities' => json_encode($item['eligible_nationalities'], JSON_UNESCAPED_UNICODE),
                    'fields_of_study' => json_encode($item['fields_of_study'], JSON_UNESCAPED_UNICODE),
                    'minimum_gpa' => $item['minimum_gpa'],
                    'language_requirements' => json_encode($item['language_requirements'], JSON_UNESCAPED_UNICODE),
                    'application_deadline' => $item['application_deadline'],
                    'start_date' => $item['start_date'],
                    'duration_months' => $item['duration_months'],
                    'application_url' => $item['application_url'],
                    'requirements' => json_encode($item['requirements'], JSON_UNESCAPED_UNICODE),
                    'benefits' => json_encode($item['benefits'], JSON_UNESCAPED_UNICODE),
                    'selection_criteria' => json_encode($item['selection_criteria'], JSON_UNESCAPED_UNICODE),
                    'application_process' => json_encode($item['application_process'], JSON_UNESCAPED_UNICODE),
                    'status' => $item['status'],
                    'is_featured' => $item['is_featured'],
                    'last_verified_at' => now(),
                ]
            );
        }
    }
}
